2018-07-17 15:22:27,044 ERROR: Exception on /index [GET] [in /data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/storage/emulated/0/Download/blog/app/routers.py", line 22, in index
    posts = current_user.followed_post().all()
  File "/storage/emulated/0/Download/blog/app/models.py", line 62, in followed_post
    own = Post.query.filter_by(user_id == self.id)
NameError: name 'user_id' is not defined
2018-07-17 15:23:26,139 INFO: Microblog startup [in /storage/emulated/0/Download/blog/app/__init__.py:33]
2018-07-17 15:23:28,782 ERROR: Exception on /index [GET] [in /data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/storage/emulated/0/Download/blog/app/routers.py", line 22, in index
    posts = current_user.followed_post().all()
  File "/storage/emulated/0/Download/blog/app/models.py", line 62, in followed_post
    own = Post.query.filter_by(id == self.id)
TypeError: filter_by() takes 1 positional argument but 2 were given
2018-07-17 15:47:19,943 INFO: Microblog startup [in /storage/emulated/0/Download/blog/app/__init__.py:33]
2018-07-17 15:47:38,927 INFO: Microblog startup [in /storage/emulated/0/Download/blog/app/__init__.py:33]
2018-07-17 15:49:05,245 INFO: Microblog startup [in /storage/emulated/0/Download/blog/app/__init__.py:33]
2018-07-17 15:55:45,760 INFO: Microblog startup [in /storage/emulated/0/Download/blog/app/__init__.py:33]
2018-07-17 15:56:12,233 INFO: Microblog startup [in /storage/emulated/0/Download/blog/app/__init__.py:33]
2018-07-17 15:58:41,210 INFO: Microblog startup [in /storage/emulated/0/Download/blog/app/__init__.py:33]
2018-07-17 15:58:57,416 INFO: Microblog startup [in /storage/emulated/0/Download/blog/app/__init__.py:33]
2018-07-17 15:59:10,993 ERROR: Exception on /index [GET] [in /data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/storage/emulated/0/Download/blog/app/routers.py", line 22, in index
    posts = current_user.followed_post().all()
  File "/storage/emulated/0/Download/blog/app/models.py", line 62, in followed_post
    own = Post.query.filter_by(user_id == self.id)
NameError: name 'user_id' is not defined
2018-07-17 16:01:17,656 INFO: Microblog startup [in /storage/emulated/0/Download/blog/app/__init__.py:33]
2018-07-17 16:04:52,848 INFO: Microblog startup [in /storage/emulated/0/Download/blog/app/__init__.py:33]
2018-07-17 16:05:45,717 INFO: Microblog startup [in /storage/emulated/0/Download/blog/app/__init__.py:33]
2018-07-17 16:06:42,141 INFO: Microblog startup [in /storage/emulated/0/Download/blog/app/__init__.py:33]
2018-07-17 16:07:34,120 INFO: Microblog startup [in /storage/emulated/0/Download/blog/app/__init__.py:33]
2018-07-17 16:07:46,848 INFO: Microblog startup [in /storage/emulated/0/Download/blog/app/__init__.py:33]
